// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaqnVYhg6a5M6N3Yc60LaAGE0TF9TwdEA',
    appId: '1:913971155323:web:5187708c5b0a73c9bf6dde',
    messagingSenderId: '913971155323',
    projectId: 'shoply-c6124',
    authDomain: 'shoply-c6124.firebaseapp.com',
    storageBucket: 'shoply-c6124.appspot.com',
    measurementId: 'G-527V79YN63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8slrd02bPtf0olkt_X9oJkNoiCq9feFk',
    appId: '1:913971155323:android:07407781dd0f45d2bf6dde',
    messagingSenderId: '913971155323',
    projectId: 'shoply-c6124',
    storageBucket: 'shoply-c6124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdTKJSvoucbobpEzB9Uyq9TlbibujTdo',
    appId: '1:913971155323:ios:0f8ef0ec0e556f3ebf6dde',
    messagingSenderId: '913971155323',
    projectId: 'shoply-c6124',
    storageBucket: 'shoply-c6124.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdTKJSvoucbobpEzB9Uyq9TlbibujTdo',
    appId: '1:913971155323:ios:0f8ef0ec0e556f3ebf6dde',
    messagingSenderId: '913971155323',
    projectId: 'shoply-c6124',
    storageBucket: 'shoply-c6124.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaqnVYhg6a5M6N3Yc60LaAGE0TF9TwdEA',
    appId: '1:913971155323:web:eec5eddd6d93fea5bf6dde',
    messagingSenderId: '913971155323',
    projectId: 'shoply-c6124',
    authDomain: 'shoply-c6124.firebaseapp.com',
    storageBucket: 'shoply-c6124.appspot.com',
    measurementId: 'G-XQPQFEN2CK',
  );

}