// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0Yc8H42N_cOfq3lFEwZpI2UVjV9tcVM',
    appId: '1:1093766514547:web:b94ef1a26b308bdc11a706',
    messagingSenderId: '1093766514547',
    projectId: 'shoply-bca60',
    authDomain: 'shoply-bca60.firebaseapp.com',
    storageBucket: 'shoply-bca60.appspot.com',
    measurementId: 'G-Y086YFYP43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcOVi1yu50hhvyDMjs1cfU8UcbJphfO2g',
    appId: '1:1093766514547:android:1cef356b958e961b11a706',
    messagingSenderId: '1093766514547',
    projectId: 'shoply-bca60',
    storageBucket: 'shoply-bca60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LV9URbDD17v0ThsUWdJBUGQz-v9Au0M',
    appId: '1:1093766514547:ios:68f3c81262b8e75211a706',
    messagingSenderId: '1093766514547',
    projectId: 'shoply-bca60',
    storageBucket: 'shoply-bca60.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LV9URbDD17v0ThsUWdJBUGQz-v9Au0M',
    appId: '1:1093766514547:ios:68f3c81262b8e75211a706',
    messagingSenderId: '1093766514547',
    projectId: 'shoply-bca60',
    storageBucket: 'shoply-bca60.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW0Yc8H42N_cOfq3lFEwZpI2UVjV9tcVM',
    appId: '1:1093766514547:web:20923d9c809fa77211a706',
    messagingSenderId: '1093766514547',
    projectId: 'shoply-bca60',
    authDomain: 'shoply-bca60.firebaseapp.com',
    storageBucket: 'shoply-bca60.appspot.com',
    measurementId: 'G-BJ61Z5ZBPR',
  );

}